# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Harsh Trivedi
# Description of the Site
description: A Tech lover Inspired by Imagination
# URL of Image of the Site
site-image: https://raw.githubusercontent.com/harsh98trivedi/harsh98trivedi.github.io/master/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Harsh Trivedi, A Tech Lover, Inspired by Imagination, Techetarian, DezineWrath, Kanpur, Design, Harsh
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://picsum.photos/720/404

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: harsh98trivedi@gmail.com
facebook_username: harsh98trivedi
twitter_username: harsh98trivedi
instagram_username: harsh98trivedi
linkedin_username: harsh98trivedi
github_username:  harsh98trivedi
youtube_channel_id: UCS3zvA_2r1iGT7MB3NVCGAw
reddit_username: harshtrivedi
behance_username: harsh98trivedi
dribbble_username: harsh98trivedi
spotify_username:

# Google Analytics
google-analytics: UA-70447982-3

# Disqus
disqus-shortname: harshtrivedi

# Name of the Author
author-name: Harsh Trivedi
# URL for the Image of the Author
author-image: https://www.github.com/harsh98trivedi.png
# 60 Words About the Author
author-about: Howdy, I'm Harsh Trivedi. I'm passionate Tech Lover from Kanpur, apart from that I'm a Graphic Designer and an OpenSource enthusiast Inspired by Imagination. Creating random beats, Playing Guitar, Rapping and Editing Videos, Tweaking and Tinkering also fall inside my interest zone.

# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://twitter.com/harsh98trivedi

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .DS_Store
  - Icon