60k0# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Soumyadeep Dey
# Description of the Site
description: A Tech Enthusiast & Coder
# URL of Image of the Site
site-image: https://raw.githubusercontent.com/soumyaexe/soumyaexe.github.io/master/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Soumyadeep Dey, A Tech Lover, Inspired by Imagination, @ISoumyadeepDey, Tech ISoumyadeepDey Twitter, X, Coder, Mobile, Editing 
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://source.unsplash.com/random/720x405?space

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: soulsoumya1234@gmail.com
facebook_username: ISoumyadeepDey 
twitter_username: ISoumyadeepDey 
instagram_username: s0umy4_xD
linkedin_username: ISoumyadeepDey 
github_username:  SoumyaEXE
youtube_channel_id: UCS3zvA_2r1iGT7MB3NVCGAw
reddit_username: SoumyadeepDey 
behance_username: ISoumyadeepDey 
dribbble_username: ISoumyadeepDey
spotify_username:

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: ISoumyadeepDey 

# Name of the Author
author-name: Soumyadeep Dey
# URL for the Image of the Author
author-image: https://www.github.com/Soumyaexe.png
# 60 Words About the Author
author-about: Howdy, I'm Soumyadeep Dey. I'm passionate Tech Lover, I Love Doing Coding!! Apart from being an ardent tech enthusiast, I love spending time on learning new tech things and exploring open-source projects.  I enjoy tweaking and tinkering with the gadgets I own, and apart from all this, I enjoy spending my time watching content from some of my favorite creators.  Playing with new software and apps acts like morphine/LSD for me. 
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://linksoumya.vercel.app

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .DS_Store
  - Icon
